[package]
name = "dbctl-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
dbctl-core = { path = "../dbctl-core" }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
